<a href="https://colab.research.google.com/github/Harshnagwani123/ML_TRAINING/blob/main/ML_DAY2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#LOGISTIC REGRESSION
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score


In [3]:
data=load_breast_cancer()
X=pd.DataFrame(data.data,columns=data.feature_names)
y=pd.Series(data.target)


In [4]:
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)


In [5]:
scaler=StandardScaler()
X_scaled_train=scaler.fit_transform(X_train)
X_scaled_test=scaler.fit_transform(X_test)


In [7]:
clf=LogisticRegression(max_iter=10000,solver='liblinear')
clf.fit(X_scaled_train,y_train)

LogisticRegression(max_iter=10000, solver='liblinear')

In [9]:
y_pred=clf.predict(X_scaled_test)
y_prd_prob=clf.predict_proba(X_scaled_test)[:,1]

In [12]:
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("ROC AUC SCORE:",roc_auc_score(y_test,y_prd_prob))

Confusion Matrix:
 [[41  1]
 [ 1 71]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        42
           1       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

ROC AUC SCORE: 0.9957010582010581


In [13]:
coefs=pd.Series(clf.coef_[0],index=X.columns)
coefs.sort_values(ascending=False)

mean compactness           0.660985
compactness error          0.650599
fractal dimension error    0.423388
symmetry error             0.349244
texture error              0.251621
mean fractal dimension     0.179213
concavity error            0.177227
worst compactness          0.049562
smoothness error          -0.164410
mean symmetry             -0.175127
worst fractal dimension   -0.181478
mean smoothness           -0.196100
concave points error      -0.428106
mean perimeter            -0.460988
mean radius               -0.493112
perimeter error           -0.546280
mean area                 -0.548171
mean texture              -0.556204
mean concavity            -0.618439
mean concave points       -0.705895
worst smoothness          -0.759567
worst perimeter           -0.764807
worst concavity           -0.827180
worst symmetry            -0.928729
worst concave points      -0.945296
worst radius              -0.946000
area error                -0.958096
worst area                -0.979282
radius error              -1.087929
worst texture             -1.242272
dtype: float64

In [14]:
coefs = pd.Series(clf.coef_[0], index=X.columns).sort_values(key=abs, ascending=False)
print(coefs.head(10))


worst texture          -1.242272
radius error           -1.087929
worst area             -0.979282
area error             -0.958096
worst radius           -0.946000
worst concave points   -0.945296
worst symmetry         -0.928729
worst concavity        -0.827180
worst perimeter        -0.764807
worst smoothness       -0.759567
dtype: float64


KNN

In [15]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [17]:
iris=load_iris()
X=pd.DataFrame(iris.data,columns=iris.feature_names)
y=pd.Series(iris.target)

In [18]:
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)

In [19]:
scaler=StandardScaler()
X_scaled_train=scaler.fit_transform(X_train)
X_scaled_test=scaler.fit_transform(X_test)

In [26]:
param_grid={'n_neighbors':list(range(1,16))}
knn=KNeighborsClassifier()
grid_search=GridSearchCV(knn,param_grid,cv=5)
grid_search.fit(X_scaled_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15]})

In [27]:
print("Best Parameters:",grid_search.best_params_)

Best Parameters: {'n_neighbors': 5}


In [28]:
bestKnn=grid_search.best_estimator_
y_pred=bestKnn.predict(X_scaled_test)

In [30]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
